# Generated by Django 4.2.5 on 2023-10-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_class_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='main_image_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_class_app.courseimage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
