# Generated by Django 4.2.5 on 2023-10-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_class_app', '0003_alter_course_main_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='main_image_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_class_app.courseimage'),
        ),
    ]
