# Generated by Django 4.2.5 on 2023-10-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_class_app', '0004_alter_course_main_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='repeat_date',
            new_name='repeat_every',
        ),
        migrations.AddField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
