# Generated by Django 4.2.5 on 2023-10-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_class_app', '0005_rename_repeat_date_classroom_repeat_every_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
