# Generated by Django 4.2.5 on 2023-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_class_app', '0006_alter_lesson_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
