# Generated by Django 4.2.5 on 2023-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_class_app', '0007_user_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
